import 'package:equatable/equatable.dart';

enum AccountingBasis { accrual }

enum MoneyUnit { rial, toman }

enum ChartTemplate { iranStandard, service, commercial, manufacturing }

class AccountingSetup extends Equatable {
  const AccountingSetup({
    required this.basis,
    required this.moneyUnit,
    required this.fiscalYearStartMonth,
    required this.chartTemplate,
    required this.autoGenerateDetailCodes,
  });

  final AccountingBasis basis;
  final MoneyUnit moneyUnit;
  final int fiscalYearStartMonth;
  final ChartTemplate chartTemplate;
  final bool autoGenerateDetailCodes;

  @override
  List<Object?> get props => [
        basis,
        moneyUnit,
        fiscalYearStartMonth,
        chartTemplate,
        autoGenerateDetailCodes
      ];
}
