name: asoud_erp
description: Iranian ERP mobile client for ERPNext/Frappe.
publish_to: none
version: 0.4.5+9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.10.0
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.4.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
