import '../entities/accounting_setup.dart';

class CompanyAccountingSettings {
  const CompanyAccountingSettings({
    required this.moneyUnit,
    required this.startDay,
    required this.startMonth,
    required this.fiscalYear,
    required this.chartTemplate,
    required this.autoGenerateDetailCodes,
  });
  final MoneyUnit moneyUnit;
  final int startDay, startMonth, fiscalYear;
  final ChartTemplate chartTemplate;
  final bool autoGenerateDetailCodes;
}

class FiscalYearInfo {
  const FiscalYearInfo({
    required this.id,
    required this.year,
    required this.startDate,
    required this.endDate,
    this.disabled = false,
  });
  final String id, year, startDate, endDate;
  final bool disabled;
}

class AccountCodeSettings {
  const AccountCodeSettings({
    required this.autoGenerate,
    required this.groupDigits,
    required this.generalDigits,
    required this.ledgerDigits,
  });
  final bool autoGenerate;
  final int groupDigits, generalDigits, ledgerDigits;
}

abstract interface class BaseSetupRepository {
  Future<CompanyAccountingSettings> getSettings(String company);
  Future<CompanyAccountingSettings> saveSettings(
      String company, CompanyAccountingSettings settings);
  Future<List<FiscalYearInfo>> getFiscalYears(String company);
  Future<FiscalYearInfo> createFiscalYear(
      String company, int year, int month, int day);
  Future<AccountCodeSettings> getAccountCodeSettings(String company);
  Future<AccountCodeSettings> saveAccountCodeSettings(
      String company, AccountCodeSettings settings);
}
