import '../entities/accounting_setup.dart';

class CompanyAccountingSettings {
  const CompanyAccountingSettings({
    required this.moneyUnit,
    required this.startDay,
    required this.startMonth,
    required this.fiscalYear,
    required this.chartTemplate,
    required this.autoGenerateDetailCodes,
  });
  final MoneyUnit moneyUnit;
  final int startDay, startMonth, fiscalYear;
  final ChartTemplate chartTemplate;
  final bool autoGenerateDetailCodes;
}

abstract interface class BaseSetupRepository {
  Future<CompanyAccountingSettings> getSettings(String company);
  Future<CompanyAccountingSettings> saveSettings(
      String company, CompanyAccountingSettings settings);
}
