import '../../../../core/network/frappe_client.dart';
import '../../../../core/config/app_config.dart';
import '../../domain/entities/office.dart';
import '../../domain/repositories/office_repository.dart';
import '../models/office_model.dart';

class FrappeOfficeRepository implements OfficeRepository {
  const FrappeOfficeRepository(this._client);

  final FrappeClient _client;

  @override
  Future<Office> createOffice(Office office) async {
    final model = OfficeModel.fromEntity(office);
    final response = await _client.callAsoudMethod<Map<String, dynamic>>(
      'asoud_erp.api.v1.setup.save_office',
      (value) => Map<String, dynamic>.from(value! as Map),
      data: model.toSetupJson(),
    );
    AppConfig.setActiveCompany(response.data['company']?.toString() ?? '');
    AppConfig.setAutoGenerateDetailCodes(response.data['auto_generate_detail_code'] == true);
    return model.copyWithName(response.data['company']?.toString() ?? office.name);
  }

  @override
  Future<Office> updateOffice(String id, Office office) async {
    final model = OfficeModel.fromEntity(office);
    final response = await _client.callAsoudMethod<Map<String, dynamic>>(
      'asoud_erp.api.v1.setup.save_office',
      (value) => Map<String, dynamic>.from(value! as Map),
      data: {...model.toSetupJson(), 'company': id},
    );
    AppConfig.setActiveCompany(response.data['company']?.toString() ?? id);
    AppConfig.setAutoGenerateDetailCodes(response.data['auto_generate_detail_code'] == true);
    return model.copyWithName(response.data['company']?.toString() ?? id);
  }
}

