import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../../core/theme/asoud_colors.dart';
import '../../../../core/config/app_config.dart';
import '../../domain/entities/accounting_setup.dart';
import '../../domain/repositories/setup_repository.dart';
import '../bloc/base_setup_cubit.dart';
import 'roles_setup_page.dart';

class BaseAccountingSetupPage extends StatelessWidget {
  const BaseAccountingSetupPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => BaseSetupCubit(
        context.read<SetupRepository>(),
        AppConfig.companyName,
        autoGenerateDetailCodes: AppConfig.autoGenerateDetailCodes,
      ),
      child: const _BaseAccountingSetupView(),
    );
  }
}

class _BaseAccountingSetupView extends StatelessWidget {
  const _BaseAccountingSetupView();

  @override
  Widget build(BuildContext context) {
    return BlocListener<BaseSetupCubit, BaseSetupState>(
      listener: (context, state) {
        if (state.status == BaseSetupStatus.success) {
          Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => const RolesSetupPage()));
        } else if (state.status == BaseSetupStatus.failure) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(state.errorMessage ?? 'ذخیره تنظیمات انجام نشد.')),
          );
        }
      },
      child: Scaffold(
      appBar: AppBar(title: const Text('تنظیمات پایه حسابداری')),
      body: SafeArea(child: BlocBuilder<BaseSetupCubit, BaseSetupState>(builder: (context, state) {
        return ListView(padding: const EdgeInsets.all(20), children: [
          const _SectionTitle(icon: Icons.account_balance_wallet_rounded, color: AsoudColors.accounting, title: 'مبنای حسابداری'),
          const Card(
            elevation: 0,
            color: Colors.white,
            child: ListTile(
              leading: Icon(Icons.check_circle_rounded, color: AsoudColors.success),
              title: Text('حسابداری تعهدی', style: TextStyle(fontWeight: FontWeight.w700)),
              subtitle: Text('فاکتورها، بدهی‌ها و مطالبات هنگام ایجاد معامله ثبت می‌شوند.'),
            ),
          ),
          const SizedBox(height: 24),
          const _SectionTitle(icon: Icons.payments_rounded, color: Color(0xFF26A69A), title: 'واحد نمایش مبالغ'),
          SegmentedButton<MoneyUnit>(
            segments: const [ButtonSegment(value: MoneyUnit.rial, label: Text('ریال')), ButtonSegment(value: MoneyUnit.toman, label: Text('تومان'))],
            selected: {state.moneyUnit},
            onSelectionChanged: (value) => context.read<BaseSetupCubit>().setMoneyUnit(value.first),
          ),
          const SizedBox(height: 24),
          DropdownButtonFormField<int>(
            initialValue: state.fiscalYearStartMonth,
            decoration: const InputDecoration(labelText: 'ماه شروع سال مالی'),
            items: List.generate(12, (index) => DropdownMenuItem(value: index + 1, child: Text(_persianMonths[index]))),
            onChanged: (value) { if (value != null) context.read<BaseSetupCubit>().setFiscalMonth(value); },
          ),
          const SizedBox(height: 16),
          DropdownButtonFormField<ChartTemplate>(
            initialValue: state.chartTemplate,
            decoration: const InputDecoration(labelText: 'الگوی سرفصل حساب‌ها'),
            items: const [
              DropdownMenuItem(value: ChartTemplate.iranStandard, child: Text('استاندارد حسابداری ایران')),
              DropdownMenuItem(value: ChartTemplate.service, child: Text('شرکت خدماتی')),
              DropdownMenuItem(value: ChartTemplate.commercial, child: Text('شرکت بازرگانی')),
              DropdownMenuItem(value: ChartTemplate.manufacturing, child: Text('شرکت تولیدی')),
            ],
            onChanged: (value) { if (value != null) context.read<BaseSetupCubit>().setChartTemplate(value); },
          ),
          const SizedBox(height: 12),
          SwitchListTile(
            contentPadding: EdgeInsets.zero,
            value: state.autoGenerateDetailCodes,
            title: const Text('تولید خودکار کد تفصیلی'),
            subtitle: const Text('جزئیات قابل ویرایش و حذف باقی می‌مانند.'),
            onChanged: context.read<BaseSetupCubit>().setAutoDetailCodes,
          ),
          const SizedBox(height: 24),
          FilledButton(
            onPressed: state.status == BaseSetupStatus.saving ? null : context.read<BaseSetupCubit>().submit,
            child: state.status == BaseSetupStatus.saving
                ? const SizedBox.square(dimension: 22, child: CircularProgressIndicator(strokeWidth: 2))
                : const Text('ذخیره و ادامه'),
          ),
        ]);
      })),
    ));
  }
}

const _persianMonths = ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'];

class _SectionTitle extends StatelessWidget {
  const _SectionTitle({required this.icon, required this.color, required this.title});
  final IconData icon;
  final Color color;
  final String title;
  @override
  Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 10), child: Row(children: [Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: color.withValues(alpha: .12), borderRadius: BorderRadius.circular(10)), child: Icon(icon, color: color)), const SizedBox(width: 10), Text(title, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w700))]));
}
