import '../../../../core/network/frappe_client.dart';
import '../../domain/entities/accounting_setup.dart';
import '../../domain/repositories/base_setup_repository.dart';

class FrappeBaseSetupRepository implements BaseSetupRepository {
  const FrappeBaseSetupRepository(this._client);
  final FrappeApiClient _client;

  @override
  Future<CompanyAccountingSettings> getSettings(String company) async {
    final data = await _client.callAsoudMethod(
      'asoud_erp.api.v1.setup.get_company_settings',
      data: {'company': company},
    );
    return _parse(data);
  }

  @override
  Future<CompanyAccountingSettings> saveSettings(
      String company, CompanyAccountingSettings settings) async {
    final data = await _client.callAsoudMethod(
      'asoud_erp.api.v1.setup.update_company_settings',
      data: {
        'company': company,
        'display_currency':
            settings.moneyUnit == MoneyUnit.rial ? 'Rial' : 'Toman',
        'fiscal_year_start_day': settings.startDay,
        'fiscal_year_start_month': settings.startMonth,
        'fiscal_year': settings.fiscalYear,
        'chart_template': _template(settings.chartTemplate),
        'auto_generate_detail_code': settings.autoGenerateDetailCodes ? 1 : 0,
      },
    );
    return _parse(data);
  }

  CompanyAccountingSettings _parse(dynamic raw) {
    if (raw is! Map) throw StateError('Invalid setup response');
    final data = Map<String, dynamic>.from(raw);
    return CompanyAccountingSettings(
      moneyUnit: data['display_currency'] == 'Toman'
          ? MoneyUnit.toman
          : MoneyUnit.rial,
      startDay: (data['fiscal_year_start_day'] as num?)?.toInt() ?? 1,
      startMonth: (data['fiscal_year_start_month'] as num?)?.toInt() ?? 1,
      fiscalYear: int.tryParse(data['fiscal_year']?.toString() ?? '') ?? 1405,
      chartTemplate: _templateFromApi(data['chart_template']?.toString()),
      autoGenerateDetailCodes: data['auto_generate_detail_code'] != false,
    );
  }

  String _template(ChartTemplate value) => switch (value) {
        ChartTemplate.iranStandard => 'Iran Standard',
        ChartTemplate.service => 'Service',
        ChartTemplate.commercial => 'Commercial',
        ChartTemplate.manufacturing => 'Manufacturing',
      };

  ChartTemplate _templateFromApi(String? value) => switch (value) {
        'Service' => ChartTemplate.service,
        'Commercial' => ChartTemplate.commercial,
        'Manufacturing' => ChartTemplate.manufacturing,
        _ => ChartTemplate.iranStandard,
      };
}
