import 'dart:convert';

import '../../../../core/config/app_config.dart';
import '../../../../core/network/frappe_client.dart';
import '../../domain/entities/accounting_setup.dart';
import '../../domain/entities/setup_status.dart';
import '../../domain/repositories/setup_repository.dart';

class FrappeSetupRepository implements SetupRepository {
  const FrappeSetupRepository(this._client);
  final FrappeClient _client;

  @override
  Future<SetupStatus> getStatus({String? company}) async {
    final response = await _client.callAsoudMethod<Map<String, dynamic>>(
      'asoud_erp.api.v1.setup.get_setup_status',
      _map,
      data: {if (company?.isNotEmpty ?? false) 'company': company},
    );
    return _remember(response.data);
  }

  @override
  Future<SetupStatus> saveAccounting(String company, AccountingSetup setup) async {
    final response = await _client.callAsoudMethod<Map<String, dynamic>>(
      'asoud_erp.api.v1.setup.update_company_settings',
      _map,
      data: {
        'company': company,
        'display_currency': setup.moneyUnit == MoneyUnit.toman ? 'Toman' : 'Rial',
        'fiscal_year_start_month': setup.fiscalYearStartMonth,
        'chart_template': switch (setup.chartTemplate) {
          ChartTemplate.iranStandard => 'Iran Standard',
          ChartTemplate.service => 'Service',
          ChartTemplate.commercial => 'Commercial',
          ChartTemplate.manufacturing => 'Manufacturing',
        },
        'auto_generate_detail_code': setup.autoGenerateDetailCodes ? 1 : 0,
      },
    );
    return _remember(response.data);
  }

  @override
  Future<SetupStatus> saveEnabledRoles(String company, Set<String> roles) async {
    final response = await _client.callAsoudMethod<Map<String, dynamic>>(
      'asoud_erp.api.v1.setup.update_enabled_roles',
      _map,
      data: {'company': company, 'roles': jsonEncode(roles.toList())},
    );
    return _remember(response.data);
  }

  SetupStatus _remember(Map<String, dynamic> data) {
    final status = SetupStatus.fromJson(data);
    if (status.company != null) AppConfig.setActiveCompany(status.company!);
    AppConfig.setAutoGenerateDetailCodes(data['auto_generate_detail_code'] != false);
    return status;
  }

  static Map<String, dynamic> _map(Object? value) => Map<String, dynamic>.from(value! as Map);
}
