abstract final class AppConfig {
  static const erpNextBaseUrl = String.fromEnvironment(
    'ERPNEXT_BASE_URL',
    defaultValue: 'https://erp.example.com',
  );

  static const apiKey = String.fromEnvironment('ERPNEXT_API_KEY');
  static const apiSecret = String.fromEnvironment('ERPNEXT_API_SECRET');
  static const _fallbackCompanyName = String.fromEnvironment(
    'ERPNEXT_COMPANY',
    defaultValue: 'ASOUD',
  );

  static String _activeCompany = _fallbackCompanyName;
  static bool autoGenerateDetailCodes = true;
  static String get companyName => _activeCompany;
  static void setActiveCompany(String value) {
    if (value.trim().isNotEmpty) _activeCompany = value.trim();
  }

  static void setAutoGenerateDetailCodes(bool value) => autoGenerateDetailCodes = value;

  static bool get hasApiCredentials => apiKey.isNotEmpty && apiSecret.isNotEmpty;
}
