part of 'base_setup_cubit.dart';

enum BaseSetupStatus { editing, saving, success, failure }

class BaseSetupState extends Equatable {
  const BaseSetupState({
    this.basis = AccountingBasis.accrual,
    this.moneyUnit = MoneyUnit.rial,
    this.fiscalYearStartMonth = 1,
    this.fiscalYearStartDay = 1,
    this.fiscalYear = 1405,
    this.chartTemplate = ChartTemplate.iranStandard,
    this.autoGenerateDetailCodes = true,
    this.status = BaseSetupStatus.editing,
    this.message,
  });

  final AccountingBasis basis;
  final MoneyUnit moneyUnit;
  final int fiscalYearStartMonth;
  final int fiscalYearStartDay;
  final int fiscalYear;
  final ChartTemplate chartTemplate;
  final bool autoGenerateDetailCodes;
  final BaseSetupStatus status;
  final String? message;

  BaseSetupState copyWith(
      {AccountingBasis? basis,
      MoneyUnit? moneyUnit,
      int? fiscalYearStartMonth,
      int? fiscalYearStartDay,
      int? fiscalYear,
      ChartTemplate? chartTemplate,
      bool? autoGenerateDetailCodes,
      BaseSetupStatus? status,
      String? message,
      bool clearMessage = false}) {
    return BaseSetupState(
      basis: basis ?? this.basis,
      moneyUnit: moneyUnit ?? this.moneyUnit,
      fiscalYearStartMonth: fiscalYearStartMonth ?? this.fiscalYearStartMonth,
      fiscalYearStartDay: fiscalYearStartDay ?? this.fiscalYearStartDay,
      fiscalYear: fiscalYear ?? this.fiscalYear,
      chartTemplate: chartTemplate ?? this.chartTemplate,
      autoGenerateDetailCodes:
          autoGenerateDetailCodes ?? this.autoGenerateDetailCodes,
      status: status ?? BaseSetupStatus.editing,
      message: clearMessage ? null : message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [
        basis,
        moneyUnit,
        fiscalYearStartMonth,
        fiscalYearStartDay,
        fiscalYear,
        chartTemplate,
        autoGenerateDetailCodes,
        status,
        message,
      ];
}
