import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';

import '../../domain/entities/accounting_setup.dart';
import '../../domain/repositories/base_setup_repository.dart';

part 'base_setup_state.dart';

class BaseSetupCubit extends Cubit<BaseSetupState> {
  BaseSetupCubit({this.repository, this.company, this.offlinePreview = false})
      : super(const BaseSetupState());

  final BaseSetupRepository? repository;
  final String? company;
  final bool offlinePreview;

  Future<void> load() async {
    if (repository == null || company == null || offlinePreview) return;
    emit(state.copyWith(status: BaseSetupStatus.saving, clearMessage: true));
    try {
      final settings = await repository!.getSettings(company!);
      emit(state.copyWith(
        moneyUnit: settings.moneyUnit,
        fiscalYearStartDay: settings.startDay,
        fiscalYearStartMonth: settings.startMonth,
        fiscalYear: settings.fiscalYear,
        chartTemplate: settings.chartTemplate,
        autoGenerateDetailCodes: settings.autoGenerateDetailCodes,
      ));
    } catch (_) {
      emit(state.copyWith(
        status: BaseSetupStatus.failure,
        message: 'دریافت تنظیمات مالی از ERPNext انجام نشد.',
      ));
    }
  }

  void setMoneyUnit(MoneyUnit value) => emit(state.copyWith(moneyUnit: value));
  void setFiscalMonth(int value) =>
      emit(state.copyWith(fiscalYearStartMonth: value));
  void setFiscalDay(int value) =>
      emit(state.copyWith(fiscalYearStartDay: value));
  void setFiscalYear(int value) => emit(state.copyWith(fiscalYear: value));
  void setChartTemplate(ChartTemplate value) =>
      emit(state.copyWith(chartTemplate: value));
  void setAutoDetailCodes(bool value) =>
      emit(state.copyWith(autoGenerateDetailCodes: value));
  Future<bool> submit() async {
    if (offlinePreview || repository == null || company == null) {
      emit(state.copyWith(
        status: BaseSetupStatus.failure,
        message: 'پیش‌نمایش آفلاین؛ تنظیمات روی سرور ذخیره نشد.',
      ));
      return false;
    }
    emit(state.copyWith(status: BaseSetupStatus.saving, clearMessage: true));
    try {
      final saved = await repository!.saveSettings(
        company!,
        CompanyAccountingSettings(
          moneyUnit: state.moneyUnit,
          startDay: state.fiscalYearStartDay,
          startMonth: state.fiscalYearStartMonth,
          fiscalYear: state.fiscalYear,
          chartTemplate: state.chartTemplate,
          autoGenerateDetailCodes: state.autoGenerateDetailCodes,
        ),
      );
      emit(state.copyWith(
        status: BaseSetupStatus.success,
        moneyUnit: saved.moneyUnit,
        fiscalYearStartDay: saved.startDay,
        fiscalYearStartMonth: saved.startMonth,
        fiscalYear: saved.fiscalYear,
        chartTemplate: saved.chartTemplate,
        autoGenerateDetailCodes: saved.autoGenerateDetailCodes,
      ));
      return true;
    } catch (_) {
      emit(state.copyWith(
        status: BaseSetupStatus.failure,
        message: 'ذخیره تنظیمات مالی در ERPNext انجام نشد.',
      ));
      return false;
    }
  }
}
