import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';

import '../../domain/entities/accounting_setup.dart';

part 'base_setup_state.dart';

class BaseSetupCubit extends Cubit<BaseSetupState> {
  BaseSetupCubit() : super(const BaseSetupState());

  void setMoneyUnit(MoneyUnit value) => emit(state.copyWith(moneyUnit: value));
  void setFiscalMonth(int value) => emit(state.copyWith(fiscalYearStartMonth: value));
  void setChartTemplate(ChartTemplate value) => emit(state.copyWith(chartTemplate: value));
  void setAutoDetailCodes(bool value) => emit(state.copyWith(autoGenerateDetailCodes: value));
  void submit() => emit(state.copyWith(status: BaseSetupStatus.success));
}
