part of 'base_setup_cubit.dart';

enum BaseSetupStatus { editing, saving, success, failure }

class BaseSetupState extends Equatable {
  const BaseSetupState({
    this.basis = AccountingBasis.accrual,
    this.moneyUnit = MoneyUnit.rial,
    this.fiscalYearStartMonth = 1,
    this.chartTemplate = ChartTemplate.iranStandard,
    this.autoGenerateDetailCodes = true,
    this.status = BaseSetupStatus.editing,
    this.errorMessage,
  });

  final AccountingBasis basis;
  final MoneyUnit moneyUnit;
  final int fiscalYearStartMonth;
  final ChartTemplate chartTemplate;
  final bool autoGenerateDetailCodes;
  final BaseSetupStatus status;
  final String? errorMessage;

  BaseSetupState copyWith({AccountingBasis? basis, MoneyUnit? moneyUnit, int? fiscalYearStartMonth, ChartTemplate? chartTemplate, bool? autoGenerateDetailCodes, BaseSetupStatus? status, String? errorMessage, bool clearError = false}) {
    return BaseSetupState(
      basis: basis ?? this.basis,
      moneyUnit: moneyUnit ?? this.moneyUnit,
      fiscalYearStartMonth: fiscalYearStartMonth ?? this.fiscalYearStartMonth,
      chartTemplate: chartTemplate ?? this.chartTemplate,
      autoGenerateDetailCodes: autoGenerateDetailCodes ?? this.autoGenerateDetailCodes,
      status: status ?? BaseSetupStatus.editing,
      errorMessage: clearError ? null : errorMessage ?? this.errorMessage,
    );
  }

  @override
  List<Object?> get props => [basis, moneyUnit, fiscalYearStartMonth, chartTemplate, autoGenerateDetailCodes, status, errorMessage];
}

