import 'package:asoud_erp/core/theme/asoud_theme.dart';
import 'package:asoud_erp/features/base_setup/domain/repositories/base_setup_repository.dart';
import 'package:asoud_erp/features/base_setup/domain/entities/accounting_setup.dart';
import 'package:asoud_erp/features/base_setup/presentation/pages/fiscal_years_page.dart';
import 'package:asoud_erp/features/base_setup/presentation/pages/base_accounting_setup_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  for (final width in [360.0, 390.0, 430.0]) {
    testWidgets('صفحه سال مالی در عرض $width بدون overflow است',
        (tester) async {
      await tester.binding.setSurfaceSize(Size(width, 844));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(MaterialApp(
        locale: const Locale('fa'),
        theme: AsoudTheme.light,
        home: Directionality(
          textDirection: TextDirection.rtl,
          child: FiscalYearsPage(
            company: 'شرکت نمونه',
            repository: _FakeBaseSetupRepository(),
          ),
        ),
      ));
      await tester.pumpAndSettle();
      expect(find.text('ایجاد سال مالی'), findsWidgets);
      expect(find.text('سال مالی ۱۴۰۵'), findsOneWidget);
      expect(tester.takeException(), isNull);
    });
  }

  testWidgets('تنظیمات مالی الگوی کد Company را نمایش می‌دهد', (tester) async {
    await tester.binding.setSurfaceSize(const Size(390, 844));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(MaterialApp(
      locale: const Locale('fa'),
      theme: AsoudTheme.light,
      home: Directionality(
        textDirection: TextDirection.rtl,
        child: AccountingPreferencesPage(
          officeName: 'شرکت نمونه',
          repository: _FakeBaseSetupRepository(),
        ),
      ),
    ));
    await tester.pumpAndSettle();
    expect(find.text('الگوی کد سرفصل‌ها'), findsOneWidget);
    expect(find.text('تولید خودکار کد حساب'), findsOneWidget);
    expect(find.text('سال مالی و تاریخ شروع'), findsOneWidget);
    expect(tester.takeException(), isNull);
    await expectLater(
      find.byType(AccountingPreferencesPage),
      matchesGoldenFile('goldens/financial_settings_390.png'),
    );
  });
}

class _FakeBaseSetupRepository implements BaseSetupRepository {
  @override
  Future<AccountCodeSettings> getAccountCodeSettings(String company) async =>
      const AccountCodeSettings(
          autoGenerate: true,
          groupDigits: 1,
          generalDigits: 2,
          ledgerDigits: 2);

  @override
  Future<AccountCodeSettings> saveAccountCodeSettings(
          String company, AccountCodeSettings settings) async =>
      settings;
  @override
  Future<List<FiscalYearInfo>> getFiscalYears(String company) async => const [
        FiscalYearInfo(
          id: '1405',
          year: '1405',
          startDate: '2026-03-21',
          endDate: '2027-03-20',
        ),
      ];

  @override
  Future<FiscalYearInfo> createFiscalYear(
          String company, int year, int month, int day) async =>
      const FiscalYearInfo(
        id: '1405',
        year: '1405',
        startDate: '2026-03-21',
        endDate: '2027-03-20',
      );

  @override
  Future<CompanyAccountingSettings> getSettings(String company) =>
      Future.value(const CompanyAccountingSettings(
        moneyUnit: MoneyUnit.rial,
        startDay: 1,
        startMonth: 1,
        fiscalYear: 1405,
        chartTemplate: ChartTemplate.iranStandard,
        autoGenerateDetailCodes: true,
      ));

  @override
  Future<CompanyAccountingSettings> saveSettings(
          String company, CompanyAccountingSettings settings) async =>
      settings;
}
