import 'package:asoud_erp/core/network/api_exception.dart';
import 'package:asoud_erp/core/offline/local_record.dart';
import 'package:asoud_erp/features/base_setup/data/repositories/server_first_base_setup_repository.dart';
import 'package:asoud_erp/features/base_setup/domain/entities/accounting_setup.dart';
import 'package:asoud_erp/features/base_setup/domain/repositories/base_setup_repository.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../helpers/fake_local_record_store.dart';

void main() {
  const settings = CompanyAccountingSettings(
    moneyUnit: MoneyUnit.toman,
    startDay: 1,
    startMonth: 1,
    fiscalYear: 1405,
    chartTemplate: ChartTemplate.iranStandard,
    autoGenerateDetailCodes: true,
  );

  test('تنظیمات سالم ابتدا روی سرور و سپس به‌صورت synced ذخیره می‌شود',
      () async {
    final local = FakeLocalRecordStore();
    final remote = _BaseRepository(settings);
    final repository = ServerFirstBaseSetupRepository(remote, local: local);

    await repository.saveSettings('دفتر', settings);

    expect(remote.saveCalls, 1);
    expect(local.records.values.single.status, LocalSyncStatus.synced);
  });

  test('تنظیمات در نبود اتصال pending می‌شود و از کش خوانده می‌شود', () async {
    final local = FakeLocalRecordStore();
    final remote = _BaseRepository(settings, error: _networkError);
    final repository = ServerFirstBaseSetupRepository(remote, local: local);

    await expectLater(
      repository.saveSettings('دفتر', settings),
      throwsA(_networkError),
    );

    expect(local.records.values.single.status, LocalSyncStatus.pendingSync);
    expect((await repository.getSettings('دفتر')).fiscalYear, 1405);
  });
}

const _networkError = ApiException(
  kind: ApiFailureKind.network,
  message: 'offline',
);

class _BaseRepository implements BaseSetupRepository {
  _BaseRepository(this.settings, {this.error});
  final CompanyAccountingSettings settings;
  final ApiException? error;
  int saveCalls = 0;

  void _check() {
    if (error != null) throw error!;
  }

  @override
  Future<CompanyAccountingSettings> getSettings(String company) async {
    _check();
    return settings;
  }

  @override
  Future<CompanyAccountingSettings> saveSettings(
    String company,
    CompanyAccountingSettings value,
  ) async {
    saveCalls++;
    _check();
    return value;
  }

  @override
  Future<AccountCodeSettings> getAccountCodeSettings(String company) async {
    _check();
    return const AccountCodeSettings(
      autoGenerate: true,
      groupDigits: 1,
      generalDigits: 2,
      ledgerDigits: 2,
    );
  }

  @override
  Future<AccountCodeSettings> saveAccountCodeSettings(
    String company,
    AccountCodeSettings value,
  ) async {
    _check();
    return value;
  }

  @override
  Future<FiscalYearInfo> createFiscalYear(
    String company,
    int year,
    int month,
    int day,
  ) async {
    _check();
    return FiscalYearInfo(
      id: '$company-$year',
      year: '$year',
      startDate: '$year-$month-$day',
      endDate: '',
    );
  }

  @override
  Future<List<FiscalYearInfo>> getFiscalYears(String company) async {
    _check();
    return const [];
  }
}
