import 'package:asoud_erp/core/offline/queued_offline_exception.dart';
import 'package:asoud_erp/core/theme/asoud_theme.dart';
import 'package:asoud_erp/core/widgets/asoud_form.dart';
import 'package:asoud_erp/features/workflows/data/generic_request_repository.dart';
import 'package:asoud_erp/features/workflows/domain/entities/request_models.dart';
import 'package:asoud_erp/features/workflows/presentation/pages/generic_request_page.dart';
import 'package:asoud_erp/features/workflows/presentation/pages/request_flow_pages.dart';
import 'package:asoud_erp/features/workflows/presentation/request_screen_registry.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'request_fixtures.dart';

class _Repo extends Mock implements GenericRequestRepository {}

Map<String, dynamic> _type(String template) => requestOptionFixtures()
    .firstWhere((row) => row['template_key'] == template);

_Repo _repo() {
  final repo = _Repo();
  when(() => repo.options()).thenAnswer((_) async => requestOptionFixtures());
  when(() => repo.fieldOptions('Leave Type', txt: any(named: 'txt')))
      .thenAnswer((_) async => [
            {'value': 'Casual Leave', 'label': 'سالانه'}
          ]);
  when(() => repo.listPage(
          templateKey: any(named: 'templateKey'),
          statusGroup: any(named: 'statusGroup'),
          search: any(named: 'search'),
          offset: any(named: 'offset'),
          limit: any(named: 'limit'),
          priority: any(named: 'priority'),
          dateFrom: any(named: 'dateFrom'),
          dateTo: any(named: 'dateTo')))
      .thenAnswer((_) async => const RequestListPage.empty());
  when(() => repo.pending()).thenAnswer((_) async => []);
  return repo;
}

Widget _app(Widget home) => MaterialApp(
    theme: AsoudTheme.light,
    builder: (context, child) =>
        Directionality(textDirection: TextDirection.rtl, child: child!),
    home: home);

void main() {
  setUp(RequestScreenRegistry.clear);
  setUpAll(() => registerFallbackValue(<String, dynamic>{}));

  testWidgets(
      'a system template opened in the generic form sends template_key and no derived fields',
      (tester) async {
    await tester.binding.setSurfaceSize(const Size(430, 2400));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    final repo = _repo();
    Map<String, dynamic>? sent;
    when(() => repo.create(any(), any())).thenAnswer((call) async {
      sent = Map.from(call.positionalArguments.first as Map);
      return null;
    });
    await tester.pumpWidget(
        _app(GenericRequestPage(repository: repo, definition: _type('leave'))));
    await tester.pumpAndSettle();
    // The subject is generated by the server: there is no title box and no
    // priority / project section.
    expect(find.widgetWithText(TextFormField, 'عنوان درخواست *'), findsNothing);
    expect(find.text('اطلاعات تکمیلی (اختیاری)'), findsNothing);
    // Daily is the default; the hourly block is hidden.
    expect(find.text('تاریخ شروع'), findsOneWidget);
    expect(find.text('ساعت شروع'), findsNothing);

    await tester.tap(find.widgetWithText(InputDecorator, 'نوع مرخصی'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('سالانه'));
    await tester.pumpAndSettle();
    await tester.enterText(
        find.widgetWithText(TextFormField, 'تاریخ شروع'), '۱۴۰۵/۰۷/۱۸');
    await tester.enterText(
        find.widgetWithText(TextFormField, 'تاریخ پایان'), '۱۴۰۵/۰۷/۲۰');
    await tester.enterText(
        find.widgetWithText(TextFormField, 'دلیل مرخصی'), 'سفر شخصی');
    await tester.pumpAndSettle();
    tester.widget<AsoudFormPage>(find.byType(AsoudFormPage)).onSave();
    await tester.pumpAndSettle();
    await tester.tap(find.descendant(
        of: find.byType(AlertDialog), matching: find.byType(FilledButton)));
    await tester.pumpAndSettle();

    expect(sent!['template_key'], 'leave');
    expect(sent!['workflow_definition'], 'SYS-LEAVE-WP');
    expect(sent!['subject'], '');
    expect(
        sent!.keys,
        isNot(anyOf(contains('priority'), contains('project'),
            contains('department'), contains('required_by'))));
    expect(sent!['attachments'], isEmpty);
    final values = sent!['values'] as Map;
    expect(values['leave_type'], 'Casual Leave');
    expect(values['request_kind'], 'Daily');
    expect(values['start_date'], '2026-10-10');
    expect(values['end_date'], '2026-10-12');
    expect(values['reason'], 'سفر شخصی');
    expect(values['requester'], 'sara@x');
    expect(values.containsKey('duration'), isFalse);
    expect(values.containsKey('start_time'), isFalse);
    expect(find.byType(RequestSubmittedPage), findsOneWidget);
  });

  testWidgets('an edit that is queued offline closes with the saved message',
      (tester) async {
    final repo = _repo();
    when(() => repo.update(any(), any(), any()))
        .thenThrow(const QueuedOfflineException(localId: 'q'));
    var closed = false;
    await tester.pumpWidget(_app(Builder(
        builder: (context) => Scaffold(
            body: Center(
                child: FilledButton(
                    onPressed: () async {
                      closed = await Navigator.push<bool>(
                              context,
                              MaterialPageRoute(
                                  builder: (_) => GenericRequestPage(
                                          repository: repo,
                                          definition: {
                                            'name': 'custom',
                                            'workflow_title': 'درخواست آزمایشی',
                                            'fields': [
                                              {
                                                'key': 'note',
                                                'label': 'یادداشت',
                                                'type': 'Short Text'
                                              }
                                            ]
                                          },
                                          existing: {
                                            'name': 'REQ-00001',
                                            'subject': 'عنوان قبلی',
                                            'values': {'note': 'x'}
                                          }))) ??
                          false;
                    },
                    child: const Text('باز کن')))))));
    await tester.tap(find.text('باز کن'));
    await tester.pumpAndSettle();
    expect(find.text('ویرایش درخواست'), findsOneWidget);
    await tester.tap(find.text('ذخیره تغییرات'));
    await tester.pumpAndSettle();
    expect(find.text('ذخیره شد؛ پس از اتصال ارسال می‌شود'), findsOneWidget);
    expect(find.text('ویرایش درخواست'), findsNothing, reason: 'page closed');
    expect(closed, isTrue);
  });

  testWidgets(
      'the generic list filters by template and creates through the registry',
      (tester) async {
    await tester.binding.setSurfaceSize(const Size(390, 900));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    final repo = _repo();
    Map<String, dynamic>? opened;
    RequestScreenRegistry.register('leave',
        RequestTemplateScreens(form: (context, repository, type, existing) {
      opened = type;
      return Scaffold(
          body: Center(
              child: FilledButton(
                  onPressed: () => Navigator.pop(context, true),
                  child: const Text('ثبت'))));
    }));
    await tester.pumpWidget(
        _app(GenericRequestsPage(company: 'Wind Power LLC', repository: repo)));
    await tester.pumpAndSettle();
    // Template filter: only the system templates are offered.
    expect(find.widgetWithText(ChoiceChip, 'همه انواع'), findsOneWidget);
    expect(find.widgetWithText(ChoiceChip, 'درخواست مرخصی'), findsOneWidget);
    await tester.tap(find.widgetWithText(ChoiceChip, 'درخواست مرخصی'));
    await tester.pumpAndSettle();
    verify(() => repo.listPage(
        templateKey: 'leave',
        statusGroup: any(named: 'statusGroup'),
        search: any(named: 'search'),
        offset: any(named: 'offset'),
        limit: any(named: 'limit'),
        priority: any(named: 'priority'),
        dateFrom: any(named: 'dateFrom'),
        dateTo: any(named: 'dateTo'))).called(greaterThan(0));

    // The new-request sheet lists the system templates first.
    await tester.tap(find.text('درخواست جدید'));
    await tester.pumpAndSettle();
    final titles = [
      for (final tile in tester.widgetList<ListTile>(find.descendant(
          of: find.byType(BottomSheet), matching: find.byType(ListTile))))
        (tile.title as Text).data
    ];
    expect(titles.first, 'درخواست خرید کالا');
    await tester.tap(find.text('درخواست مرخصی').last);
    await tester.pumpAndSettle();
    expect(opened!['template_key'], 'leave');
    await tester.tap(find.text('ثبت'));
    await tester.pumpAndSettle();
    expect(find.text('درخواست‌های من'), findsOneWidget);
  });
}
